version: "3.5"
services:
  badk_official:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn config.wsgi:application
             --bind 0.0.0.0:8000
             --workers 6
             --timeout 30
             --access-logfile -
             --error-logfile -"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  celery_worker:
    build:
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info --concurrency=4
    restart: always
    env_file:
      - ./.env
    depends_on:
      - badk_official
      - postgres
      - redis

  celery_beat:
    build:
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    env_file:
      - ./.env
    depends_on:
      - badk_official
      - postgres
      - redis

  postgres:
    image: postgres:14.6-alpine
    restart: always
    container_name: badk-db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ../badk-db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  redis:
    image: redis:7.0-alpine
    container_name: badk-redis
    restart: always
    hostname: redis